services:
  backend:
    build: ./backend
    container_name: stacknote-backend
    ports:
      - "8010:8000" # Avoid conflict (8000) -> 8010
    volumes:
      - ./backend/sql_app.db:/app/sql_app.db
      - ./backend/app:/app/app
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  voice-backend:
    build: ./voice-backend
    container_name: stacknote-voice-backend
    ports:
      - "8011:8000" # Voice 8011
    volumes:
      - ./voice-backend/app:/app/app
    restart: always

  frontend:
    build: ./frontend
    container_name: stacknote-frontend
    ports:
      - "8012:5173" # Avoid conflict (8080) -> 8012
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: always

  db:
    image: mysql:8.4
    container_name: stacknote-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306" # Avoid conflict (3306) -> 3307
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data:
